version: '3.3'
services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'onskeskyendb'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testsecret'
      MYSQL_ROOT_PASSWORD: 'testrootsecret'
    ports:
      - '3306:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
volumes:
  my-db: